### PR TITLE
Use iterable type hints

### PR DESCRIPTION
**Pull request by internalsystemerror**
To allow the RoleInterface getChildren() and getParents() methods to return a traversable object as well as an array.

Anyone else interested in this? If so I can look at adding a test, not sure if its required though?

### CODE REVIEW

**Comment by ezimuel** [comment]
@internalsystemerror this is interesting. Can you provide a uni test for this new feature? Thanks!

**Comment by ezimuel** [comment]
@internalsystemerror actually a unit test is not needed, thanks to the [Iterable Type Variance](http://php.net/manual/en/language.types.iterable.php#language.types.iterable.variance).

**Comment by ezimuel** [comment]
@internalsystemerror Thanks!

**Comment by internalsystemerror** [comment]
@ezimuel np, although i did nothing. i did check the php version that iterable types were supported. tx for the merge

**Pull request merged**
